version: "3.8"

services:
  tasmogo:
    build: .
    environment:
      - TASMOGO_DOUPDATES=true
      - TASMOGO_DAEMON=true
      - TASMOGO_CIDR=192.168.0.0/24
      - TZ=Europe/Berlin
      - TASMOGO_OTAURL=http://ota.tasmota.com/tasmota/release/
    network_mode: host
    restart: always
