version: "3.8"

services:
  tasmogo:
    build: .
    environment:
      - TASMOGO_DOUPDATES=true
      - TASMOGO_DAEMON=false
      - TASMOGO_CIDR=192.168.0.0/24
      - TASMOGO_OTAURL=http://ota.tasmota.com/tasmota
      - TZ=Europe/Berlin
    network_mode: host
    restart: always
